### ISSUE TITLE
MMRA when user navigates to a post

### ISSUE THREAD

**Issue by thebaer** [thebaer/MMRA#1]
Right now Medium is only Made Readable Again when a site first loads. This may leave readers with an un-great experience after they navigate to a post

**Comment by chris-morgan** [comment]
The proper solution for this is probably to detect Medium’s meta tag and then just inject a stylesheet via [chrome.tabs.insertCSS](https://developer.mozilla.org/en-US/Add-ons/WebExtensions/API/tabs/insertCSS).

The actual CSS will be something along the lines of

```css
.metabar.u-fixed {
	position: relative !important;
}

.js-stickyFooter,
.js-postShareWidget,
footer>.container:first-child {
	display:none !important;
}
```
