### ISSUE TITLE
Hide persistent Upgrade/"About membership" link in header

### ISSUE THREAD

**Issue by thebaer** [thebaer/MMRA#12]
![Upgrade prompts in header](https://pbs.twimg.com/media/DQD17GKUQAAAr6v.jpg)

Remove the persistent Upgrade/"About membership" link in header with:

```css
.js-upgradeMembershipAction {
  display: none;
}
```
