### ISSUE TITLE
Option to disable full-width images

### ISSUE THREAD

**Issue by waldyrious** [thebaer/MMRA#16]
Besides the massive headers (#9), one of the things that often annoys me in Medium posts is the huge, full-width images in the body of the post.

I think scaling them down to reasonable sizes can be achieved by changing the `sectionLayout--fullWidth` class to have the same definitions as the `sectionLayout--insetColumn` class, i.e.:

```css
.sectionLayout--fullWidth {
    max-width: 740px;
    margin: 0 auto;
}
```
It also helps to reduce the huge bottom margin in figure element:

```css
.graf--layoutFillWidth {
    margin-bottom: inherit;
}
```

**Comment by thebaer** [comment]
Nice, do you have an example post with a full-width image in the body? So we can all confirm the exact issue and any potential solutions.

**Comment by waldyrious** [comment]
Sure. This is the one that prompted me to open the issue: https://blog.keep.network/zero-knowledge-proofs-zcash-and-ethereum-f6d89fa7cba8

**Comment by thebaer** [comment]
Oh yeah, that's crazy. We should definitely add the option.

**Comment by Fraasi** [comment]
I thought I would try to take this, but the only thing that worked for me in your extension was header moving out of the way (in uptodate chrome & vivaldi).   
So I think I'll keep using my simple stylus script to clear all the garbage:

```css
.metabar, .u-fixed, .u-height44 {
  display: none;
}
```

Anyway, this works for me in medium site to shrink image width to paragraph width and center it.  
(does not work in above mentioned keep.network site as it uses different class names)

```css
.graf-after--p {
  width: 700px;
  margin: 0px auto;
}
```
